- hosts: all
  name: Install and setup sbideo server and transcode 
  sudo: yes

  environment:
    NODE_ENV: production
  
  tasks:
  - name: create target directory
    file: path=/tmp/sbideo state=directory

  - name: copy debian package for sbideo
    copy: src={{ item }} dest=/tmp/sbideo/sbideo.deb
    with_fileglob:
      - ../pkg/sbideo*.deb

  - name: remove sbideo debian package
    apt: name=sbideo state=absent

  - name: install debian package sbideo
    apt: deb=/tmp/sbideo/sbideo.deb state=present dpkg_options={{ dpkg_options }}

  - name: remove debian package file in tmp directory
    file: path=/tmp/sbideo state=absent
    
  - name: create logging directory
    file: path=/var/log/sbideo state=directory owner=www-data group=www-data
    
  - name: download dependencies for sbideo with npm
    shell: npm install
    args:
      chdir: /usr/lib/sbideo
        
  - name: build sbideo with npm
    shell: npm run build
    args:
      chdir: /usr/lib/sbideo
    environment:
      NODE_ENV: production
        
  - name: Add sbideo server systemd service configuration file
    copy: src=files/sbideo-server.service dest=/etc/systemd/system/sbideo-server.service owner=root group=root mode=0644
    
  - name: Add sbideo transcode systemd service configuration file
    copy: src=files/sbideo-transcode.service dest=/etc/systemd/system/sbideo-transcode.service owner=root group=root mode=0644
    
  - name: start sbideo server
    shell: systemctl start sbideo-server.service 
    
  - name: start sbideo server on bootup
    shell: systemctl enable sbideo-server.service

  - name: check - sbideo is reachable
    uri:
      url: http://{{ ansible_hostname }}:3000
      timeout: 300
    delegate_to: ansible.infra.dev.seitenbau.net
    register: result
    until: result is defined and result.status == 200
    retries: 5
    delay: 10
